dev:
  bpm-crafters:
    process-api:
      adapter:
        c8:
          user-tasks:
            delivery-strategy: subscription_refreshing
            completion-strategy: job
            schedule-delivery-fixed-rate-in-seconds: 5
